# Creates/Updates a Shopify theme and adds the preview link within the PR description and as a comment
# The first time the theme is created, event .json files within the /templates folder are pushed to the theme
# Subsequte updates to an existing theme does not push any .json files within the /templates folder
#
# @devs For notes on creating composite actions: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: "Shopify Auto Preview"
description: "Creates/Updates a Shopify theme and adds the preview link within the PR description and as a comment"
inputs:
  shopify-flag-store:
    description: "The Shopify store URL e.g. store-name.myshopify.com"
    required: true
  shopify-cli-theme-token:
    description: "The Shopify CLI theme token created via custom app"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - run: echo Hello ${{ inputs.shopify-flag-store }}.
      shell: bash
