# Creates/Updates a Shopify theme and adds the preview link within the PR description and as a comment
# The first time the theme is created, event .json files within the /templates folder are pushed to the theme
# Subsequte updates to an existing theme does not push any .json files within the /templates folder
#
# @devs For notes on creating composite actions: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: "Hello World"
description: "Greet someone"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: goodbye.sh
      shell: bash
