name: "Creates/Updates Shopify Theme"
description: "Creates/Updates a Shopify theme and returns the preview link and admin link"

inputs:
  build-production:
    description: "Build Production"
    default: false
outputs:
  preview-link:
    description: "Preview Link"
    value: ${{ steps.shopify-theme-data.outputs.preview-link }}
  editor-link:
    description: "Editor Link"
    value: ${{ steps.shopify-theme-data.outputs.editor-link }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler: "latest"

    - name: Install Shopify CLI
      run: npm install -g @shopify/cli @shopify/theme # tested using @shopify/cli@3.47.1 and @shopify/theme@3.47.1 but we don't scope the versions to see how well the task performs
      shell: bash

    - name: Set CURRENT_BRANCH
      run: |
        echo "CURRENT_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
      shell: bash

    - name: Get CURRENT_BRANCH
      run: echo ${{ env.CURRENT_BRANCH }}
      shell: bash

    - name: Build Theme
      if: ${{ inputs.build-production }}
      run: |
        npm i
        npm run build:production
      shell: bash

    - name: Shopify Name
      run: |
        echo "SHOPIFY_NAME=$(echo '${{ env.CURRENT_BRANCH }}' | cut -c1-50)" >> $GITHUB_ENV
      shell: bash

    - name: THEME_ID
      run: |
        echo "THEME_ID=$(echo $(shopify theme list | grep \${{ env.SHOPIFY_NAME }} | awk '{print $NF}' | tr -d '#'))" >> $GITHUB_ENV
      shell: bash

    - name: Create Shopify Theme
      if: ${{ env.THEME_ID == '' }}
      run: |
        echo "JSON_RESPONSE=$(echo $(shopify theme push --unpublished --json --theme='${{ env.SHOPIFY_NAME }}' --only assets/ config/ layout/ locales/ sections/ snippets/ templates/ ))" >> $GITHUB_ENV
      shell: bash

    - name: Update Shopify Theme
      if: ${{ env.THEME_ID != '' }}
      # On subsequent pushes we exclude all .json files within /templates folder so as to not override QA changes
      run: |
        echo "Theme found: UPDATE"
        echo "JSON_RESPONSE=$(echo $(shopify theme push -t ${{ env.THEME_ID }} --only assets/ config/ layout/ locales/ sections/ snippets/ templates/ --ignore templates/*json --json ))" >> $GITHUB_ENV
      shell: bash

    - name: Extract JSON Entries
      run: | # Can extract more data from response if needed
        echo ${{ env.JSON_RESPONSE }}
        echo "THEME_ID=$(echo '${{ env.JSON_RESPONSE }}' | jq -r '.theme.id')" >> $GITHUB_ENV
        echo "PREVIEW_URL=$(echo '${{ env.JSON_RESPONSE }}' | jq -r '.theme.preview_url')" >> $GITHUB_ENV
        echo "EDITOR_URL=$(echo '${{ env.JSON_RESPONSE }}' | jq -r '.theme.editor_url')" >> $GITHUB_ENV
      shell: bash

    - id: shopify-theme-data
      run: |
        echo "preview-link=$(echo $PREVIEW_URL)" >> $GITHUB_OUTPUT
        echo "editor-link=$(echo $EDITOR_URL)" >> $GITHUB_OUTPUT
      shell: bash
