name: "Attach Shopify theme to PR comment"
description: "Attaches the shopify links to the PR as a new comment"
inputs:
  preview-link:
    description: "The preview link"
    required: true
  editor-link:
    description: "The editor link"
    required: true

runs:
  using: "composite"
  steps:
    - name: Render template
      id: template
      uses: chuhlomin/render-template@v1.7 # https://github.com/marketplace/actions/render-template https://github.com/chuhlomin/render-template
      with:
        template: .github/preview-link-template.md
        vars: |
          preview_link: ${{ inputs.preview-link }}
          editor_url: ${{ inputs.editor-link }}
          timestamp: ${{ env.CURRENT_TIME }}

    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: "github-actions[bot]"
        body-includes: Preview Link

    - name: Create or Update comment
      uses: peter-evans/create-or-update-comment@v3 # https://github.com/marketplace/actions/create-or-update-comment  https://github.com/peter-evans/create-or-update-comment
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: ${{ steps.template.outputs.result }}
        edit-mode: replace
        reactions: rocket
