# Creates/Updates a Shopify theme and adds the preview link within the PR description and as a comment
# The first time the theme is created, event .json files within the /templates folder are pushed to the theme
# Subsequte updates to an existing theme does not push any .json files within the /templates folder
#
# @devs For notes on creating composite actions: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: "Auto Preview"
on:
  pull_request:

env:
  GH_TOKEN: ${{ github.token }}
  SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_FLAG_STORE }}
  SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
  SHOPIFY_CLI_TTY: 0 # https://shopify.dev/docs/themes/tools/cli/ci-cd#step-2-integrate-shopify-cli-into-your-pipeline TODO when there is a theme limit, the following should stop interactive prompts but it doesn't seem to work

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  job-test:
    runs-on: ubuntu-latest
    timeout-minutes: 3 # Increase threshold for projects that have a larger build time

    steps:
      - uses: actions/checkout@v3

      - name: Debug
        run: |
          echo * ${{ env.SHOPIFY_FLAG_STORE }}.
          echo * ${{ env.SHOPIFY_CLI_THEME_TOKEN }}.

      - id: preview-link
        uses: Jay-Plumb/shopify-theme-preview@branch # TODO
        with:
          shopify-flag-store: ${{ env.SHOPIFY_FLAG_STORE }}
          shopify-cli-theme-token: ${{ env.SHOPIFY_CLI_THEME_TOKEN }}
